// words.js
// Todas las palabras viscosas y ridículas generadas hasta ahora,
// divididas en dos mitades para mantener el formato original.

export const adjectives = [
  'blobby','gooey','squishy','wobbly','fluffy','drippy','gloopy','lumpy',
  'silly','wonky','soggy','bouncy','spongy','jiggly','splatty','smooshy',
  'wiggly','chunky','mushy','squelchy','sloppy','fuzzy','globby','puffy',
  'sticky','gunky','puddly','giggly','ploppy','squashy','gooby','ooblecky',
  'snotty','squirmy','farty','snuggy','swampy','plubby','squibbly','drooly',
  'glurpy','snubby','melted','slurpy','clumpy','flobby','flubbery','quibbly',
  'burpy','snappy','squonky','porky','wigglywig','chewy','gummy','splodgy',
  'yucky','wibbly','wobbletastic','plonky','snorty','droopy','boingy','swishy',
  'gloobly','slurpydoo','dribbly','fartywoo','snurgly','woozy','gribbly',
  'schloppy','mucky','yibbly','plunky','glonky','flumpy','slonky','drobbly',
  'zoggy','quaggy','murbly','snibbly','shlumpy','pibbly','splooshy','gnarly',
  'puddlypuff','mimsy','spluttery','nubbly','sploinky','doofy','gloingy',
  'squashylicious','snurfly','quibblesome','schlonky','wibblesplat',
  'flubtastic','squashified','swooshy','flumple','dribblesome',
  'gloopified','splooshified','schmibbly','droopity','splotchydoo',
  'clonky','squibblesplat','glompy','slurpletastic','boinglesome',
  'mushlet','squelchity','snorkly','wubbley','fizzlump','sproingy',
  'gobbly','plurple','splinky','shmooshy','slobbity','noggleish',
  'squish','fluffo','dripdrop','gloopa','lumpus','chunkle','mushmash',
  'squelcho','sloppo','fuzzle','glubby','puffo','stickydoo','puddlus',
  'gigglop','ploppo','goober','snotto','squirmo','fartybloop','snugglus',
  'swampo','plubbly','droolix','glurpus','slurpix','clumpa','flubberon',
  'quibblus','burplo','squonk','chewgus','gummix','splodgydoo','yuckle',
  'wibblo','plonkus','boinglo','swishix','dribblo','woozix','gribblon',
  'mucko','plunkix','flumple','schlonko','squashon','droopix','splooshka',
  'snurfo','snizzle','gronko','mubbly','snurflo','plorpix','snoggleon',
  'floopus','boogle','plonko','snurfunk','flarpus','snizzlefuzz','zlobbo',
  'sploinkix','fribblus','snargle','dribblon','snizzleplop','wooble',
  'splonko','glompix','sproingus','bloopus','snuzzleflop','gronkly',
  'drozzit','wumple','splortix','nogglepuff','flumpadump','schlonkus',
  'snurfunkle','boinkus','squizzle','snibblo','glonko','plubbix',
  'squoggleon','blarfo','splooshpunk','smudglus','snorpix','frobblus',
  'squashloop','morblo','dribblob','sploingo','glorkus','splarpix',
  'squishmop','nubbix','squibblo','fuzzlepuff','booglop','smooshka',
  'snurglepunk','clonko','snizzleboop','sploochus','splotto','flubbop',
  'droozle','splunkle','gnorbo','murple','snarfblop','splobbin',
  'squibblewig','gluffus','wobblorp','drizzleplop','blubble','squarfunk',
  'snorpo','sploinkadoodle','wubblelump','sproingo','gloinkus','plopchunk',
  'sproggle','sploinkaloo','squashnob','blibbix','dropple','schlumpus',
  'squarfle','snogglepus','glurble','splingo','boofus','plonkasaur',
  'splooberon','squizzlefloop','fronkus','drongo','snarpix','splonkadoodle',
  'blurfle','squabbix','snizzleklop','frobble','splurpus','squiggro',
  'glonkasaur','snorbo','plobbix','dribbleflop','sploonkle','sproobleon',
  'snuzziplex','fuzzlecrank','snorglorp','blarfonk','sploogus','drabblus',
  'splomple','gnuzzle','squarbo','sploofus','snagglo','glumphus',
  'splunkasaur','drozzlop','plorfle','snubbo','squarpunk','frabblo',
  'sploinkusmax','snizzletrump','grobblus','splungo','schmibblus',
  'snizzleflip','flopnob','squanchus','drongoid','snurfzilla',
  'splodgopolis','glomplex','booplo','snizzlewump','frumpus',
  'splurggle','squabblero','norgus','droppix','snarfopolis','flobbix',
  'snuzzlord', 'blitz'
];

export const nouns = [
  'blob','glob','glorp','gloop','splotch','splat','plop','squidge','slime',
  'goop','ooze','droplet','clot','chunk','puddle','smudge','snoot','blub',
  'plub','squash','dribble','booger','slop','boink','gob','schlop','squirt',
  'lump','nubbin','glump','splodge','schmear','wobble','sploink','puff','goo',
  'squibble','glub','splot','doodle','wobblob','glonk','snoodle','schlomp',
  'blump','splop','sploosh','snorf','muk','squidgeon','blarf','gunk','schlorp',
  'wubble','snurgle','plibble','squoggle','boof','splarf','snibble','drupple',
  'wobbin','splooble','morf','gloob','schmorgle','bloop','snorfle','glumble',
  'squoop','flob','nurgle','pobble','snerkle','schloob','snurf','drungle',
  'squabble','blibber','pob','slurm','fribble','squog','zlob','gnorp','booble',
  'sprooble','woggly','snarp','fuzzle','gloink','blib','schplort','nubble',
  'schmubble','sploinkus','grubble','snuzzle','plorp','snoggle','sploinkadoo',
  'schlorble','snurfle','plunkus','smoog','flarp','splunk','snorgle','mubble',
  'gronk','dribblop','flobble','snuzzlepuff','splotzilla','blibble','squorf',
  'sploinker','glopple','squishnub','fuzzblob','snizz','womple','squarp',
  'glurb','snaggus','ploot','schmoob','droblop','floop','snizzle','sproinkus',
  'murgblob','gnubble','squibbleton','sploober','blopster','squorgle',
  'drobble','splungus','squabblepop','flobnob','snurgblob','schloober',
  'schmorgle','snurfunk','plurple','splotzilla','schlonko','wooble',
  'schmubble','schlonkus','snurfunkle','splooshpunk','schmibblus',
  'schlumpus','snarfblop','splooberon','splonkadoodle','snizzleklop',
  'splurpus','dribbleflop','sploonkle','sproobleon','snorglorp','splomple',
  'gnuzzle','sploofus','mubbleton','splunkasaur','splodgopolis','splurggle',
  'snarfopolis','booplo'
];
